name: autonomous_sales_data_platform
version: "1.0.0"
config-version: 2
profile: autonomous_sales_data_platform

model-paths: ["models"]

models:
  autonomous_sales_data_platform:
    staging:
      +materialized: view
    mart:
      +materialized: table
